fix(ci) Fix the registry url for cloudbuild
getsentry/cdc pull request #35
Opened 2021-04-16 16:41 UTC by fpacifici

The current cloudbuild cannot push the docker image because the url is wrong.

2021-04-19 12:59 UTC, BYK requested changes
So the main issue here was using `docker push $PROJECT_ID/$REPO_NAME` which translates into `docker push sentryio/cdc`, right?

2021-04-19 12:59 UTC, BYK commented on cloudbuild_public.yaml
> +    docker pull $$SENTRY_IMAGE
Please make this `$$CDC_IMAGE` as `SENTRY_IMAGE` has a special meaning in on-premise and it will interfere.

2021-04-19 13:03 UTC, BYK commented
Also looks like we need a `getsentry/cdc` repo on Docker Hub, created.

2021-04-19 15:14 UTC, fpacifici commented
> So the main issue here was using docker push $PROJECT_ID/$REPO_NAME which translates into docker push sentryio/cdc, right?

That was an issue. But I think also creating the `getsentry/cdc` repo as you did was needed as well. Will try again today

2021-04-19 16:34 UTC, fpacifici commented
@BYK thanks for adding the repo on docker. Now it works.

2021-04-20 08:03 UTC, BYK approved these changes

2021-04-20 15:30 UTC, merged